// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Posta_Barnabas_Projekt.Data;

#nullable disable

namespace Posta_Barnabas_Projekt.Migrations
{
    [DbContext(typeof(KönyvtárAdatbázis))]
    [Migration("20250520123905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Posta_Barnabas_Projekt.Modellek.Kölcsönzés", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("KölcsönzésDátuma")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeltáriSzám")
                        .HasColumnType("int");

                    b.Property<int>("OlvasóSzám")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisszahozásDátuma")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kölcsönzések");
                });

            modelBuilder.Entity("Posta_Barnabas_Projekt.Modellek.Könyv", b =>
                {
                    b.Property<int>("LeltáriSzám")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeltáriSzám"));

                    b.Property<string>("Cím")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KiadásÉve")
                        .HasColumnType("int");

                    b.Property<string>("Kiadó")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Szerző")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeltáriSzám");

                    b.ToTable("Könyvek");
                });

            modelBuilder.Entity("Posta_Barnabas_Projekt.Modellek.Olvasó", b =>
                {
                    b.Property<int>("OlvasóSzám")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OlvasóSzám"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lakcím")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Név")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OlvasóSzám");

                    b.ToTable("Olvasók");
                });
#pragma warning restore 612, 618
        }
    }
}
